services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=weather_app
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:root@db:5432/
      - DATABASE_NAME=weather_app?ssl=disable
      - ECHO_SQL=True
      - API_BASE_URL=https://api.openweathermap.org/data/3.0/onecall
      - API_KEY=<Your API Key here>
    restart: on-failure
    depends_on:
      - db
